### PR TITLE
fix bundling with rollup

### PR DESCRIPTION
**Pull request by cvlmtg**
Hi, I'm playing a bit with @blueprint, which uses tether as a dependency. I've discovered that when I bundle the code with rollup (browserify + rollupify to be exact) tether breaks, because some functions are removed by rollup tree shaking. (If I bundle without rollup the code builds and runs fine).

I've seen you basically apply babel to each source file, concat them together and then wrap everything in an UMD module. If I invert the babel/concat plugins the new build no longer breaks with rollup. As an added bonus the babel helpers are not duplicated, so the new minified code is a bit smaller.

I've also took the liberty to do a small amount of cleanup in the code (like the use of "let" or "var").

Since there are no tests I'm not 100% sure I didn't break anything, but a couple of tests with my app show nothing wrong with the new build. Feel free to review my changes :)

Thanks in advance!

### CODE REVIEW

**Comment by yairEO** [comment]
I would suggest to split your 3rd-party scripts to a separate file and simply concatenate them, and not bundle them using Rollup, to have separation between your own code and 3rd-party dependencies. much cleaner.

I don't see a value in bundling 3rd-party scripts since they are totally independent and do not require do any cross-dependencies (like importing and using another 3rd-party script by themselves)

**Comment by cvlmtg** [comment]
If I simply concatenate all my 3rd party scripts won't that pollute the global namespace? (plus I need to change all my code to reference those modules differently).

I'd also would like to remind that my very simple change to the tether gulpfile not only fix the problem with rollup, but it also reduce the bundle size, because babel helpers don't get included more than once.

**Comment by yairEO** [comment]
you are you thinking about it as "pollution"? they are what they are, independent scripts which use the normal and standard channel of communication - the `window` object, like your app. 

if your app is entity `A` for example (`window.A`), then a 3rd party script, like D3 for example, would be `window.D3`. 

I don't see anything wrong with it.

**Comment by cvlmtg** [comment]
I see it as "pollution" because I've been taught so ;) and it may always happen that two modules try to define the same name.

In any case I think this patch would still benefit even people who likes your approach

**Comment by yairEO** [comment]
@cvlmtg - I didn't know people teach such things to other people. I find it odd. 
I wasn't taught anything. I use my brain to think what makes sense and what isn't.
in all my years of JS coding, which is about 13 and over 100 projects, I never had a situation where two modules used the same namespace. it is a situation so esoteric that using a bundler is a complete overkill, instead you can simply change one of the script's namespace in 1 minute, it is very simple.

**Comment by cvlmtg** [comment]
I think $ and _ are a couple of good examples of libraries trying to set the same name in the global namespace.

btw I've been doing this work for about 15 years and some other things I've learned is to never assume the people I disagree with don't use their brain, or that my way of doing things is the only one correct. oh and that following standards or best practices (talking about how to bundle code here) is a good thing, because it makes collaboration easier. and a fix that reduces code size and let everyone use their preferred method of working is probably a good thing too.

anyway, I don't think anyone else here might be interested in our philosophycal discussion, so let's get back on topic ;)

**Comment by yairEO** [comment]
Sorry, didn't mean to offend, I was talking about my perspective on things, and it wasn't meant to say that you, yourself, is not using the organ inside your skull. it is how we say things in my cloture. sometimes things get lost in translation for non-native-english.

**Comment by cvlmtg** [comment]
I'm non-native too and no offence taken :)

**Comment by nathancahill** [comment]
Also #175 fixes the same issue, by changing the build from concatenation to bundling.

**Comment by balloob** [comment]
So I just spend a couple of hours on exactly this issue. Here is my analysis and solution.

 - Tether `package.json` points at the unminified version
 - The unminified version contains the following code:

```javascript
// https://github.com/HubSpot/tether/blob/master/dist/js/tether.js#L223
function extend() { … }

[…]

// https://github.com/HubSpot/tether/blob/master/dist/js/tether.js#L400
TetherBase.Utils = {
  …
  extend: extend,
  …
}

[…]

// https://github.com/HubSpot/tether/blob/master/dist/js/tether.js#L439
var _TetherBase$Utils = TetherBase.Utils;
var extend = _TetherBase$Utils.extend;
```

Since `var` declarations are hoisted inside a function scope, we run into the error that `extend` is already declared. I have a [JSBin repro here](http://jsbin.com/yoyasakequ/edit?js,console)

I am still scratching my head why I can't repro this problem when [embedding Tether.js in a JSFiddle](https://jsfiddle.net/2ngb5toj/1/).

Potential solutions for Tether to fix this can be:

 - Point the `main` directive in `package.json` to the minified version
 - Use a bundler instead of concatenation

For Rollup, you can also use the following workaround in your `rollup.config.js` to use the minified version instead:

```javascript
import { rollup } from 'rollup';
import alias from 'rollup-plugin-alias';

rollup({
  entry: './src/index.js',
  plugins: [alias({
    tether: 'node_modules/tether/dist/js/tether.min.js',
  })],
});
```

**Comment by balloob** [comment]
I have forked the browserify branch and included a new build on it. As a temporary solution you can refer to Tether like this in your `package.json`:

```json
{
  "dependencies": {
    "tether": "balloob/tether#ef50f750d73e3ea025ced154967a46d760bd404f"
  }
}
```

**Comment by kopax** [comment]
Hi, I am working on a similar issue and I would like to have that fix. Is there a way to merge it so it can be included in 1.4.0 ?

**Comment by rwwagner90** [comment]
We have now migrated our internal build to rollup, so I think things should "just work" now. If anyone wants to give it a try, and report back, that would be great!

**Pull request closed without merging**
