### PR TITLE
Remove markers when tether is destroyed

### PR DESCRIPTION
**Pull request by pieter-v**
When a `tether` is created, a marker element is created and added both to. the `element` and to the `target`.
This pull request removes the markers when the `tether` is destroyed.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@pieter-v thanks for the PR! Is there a specific problem leaving the markers around is causing for you? I think they are meant to stick around.

**Comment by pieter-v** [comment]
Indeed, we have a `div` which is tethered to another one. The first `div` can be moved interactively. This is done, on a mouse-move by recreating the `tether` with a different `targetOffset`. So, the markers are pilling up.

What is the use-case for keeping the markers after the tether is destroyed?

**Comment by rwwagner90** [comment]
@pieter-v I was not involved in the implementation of this library, but I think the idea was if you wanted to show the Tether again, there would be less work to setup the markers and such? Perhaps I am wrong.

**Comment by pieter-v** [comment]
@rwwagner90 If you set up a tether again, new markers are created and the old ones are left dangling. So, I think it is safe to destroy the markers when the tether is destroyed.

**Comment by pieter-v** [comment]
Closed in favour of #1075

**Pull request closed without merging**
