### PR TITLE
Add basic tests, sass -> scss, gulp -> rollup, etc

### LINKED ISSUE #239: no version information in min.js
When tether is bundled in other projects, it's usually the minified/uglified version that is bundled.
Unfortunately this file does not contain any information about the version.
e.g. jQuery leaves this string:
`/*! jQuery v2.2.2 | (c) jQuery Foundation | jquery.org/license */`
Could you please keep such a string in tether, too?
Thanks.

Alternatively: is there a list of known tether.mini.js she-sums?

### LINKED ISSUE #256: dist/js/tether.min.js is outdated
I tried to include it in my webpack project but there was a bug where scroll top is not respected.

So somehow I managed to clone the master branch and suddenly it started working.

Just a reminder if you are encountering problems with tether.min.js please go ahead and checkout the whole repository

### PR DESCRIPTION
**Pull request by rwwagner90**
Closes #239 
Closes #256

### CODE REVIEW

**Comment by rwwagner90** [comment]
@TrevorBurnham I apologize for how many changes there are here, but a lot was needed to get things building and testing as intended. I added Jest and Cypress and just a couple super basic tests, as well as switched from gulp to rollup, and various cleanup things.

Would you perhaps be able to take a quick look and maybe also try out the dist with your apps to make sure things still work well for you? I did not intentionally change any of the API or functionality, but something could have potentially been lost in translation.

**Comment by peterblazejewicz** [comment]
Hi,
These minor additions can potentially:
- remove  linter errors from rollup config itself 

> ship-shape/prefer-destructuring from plugin:ship-shape/recommended

- remove warning about PostCSS from local and CI builds

> Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.

- remove warning about NPM/Node binaries differences from local and CI builds

> npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1568510798963-0.14485362730361873/node but npm is using /home/travis/.nvm/versions/node/v10.16.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

```diff
diff --git a/.npmrc b/.npmrc
new file mode 100644
index 0000000..5fca0d5
--- /dev/null
+++ b/.npmrc
@@ -0,0 +1 @@
+scripts-prepend-node-path=true
diff --git a/rollup.config.js b/rollup.config.js
index a837231..e20a4ba 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -23,7 +23,7 @@ const sassOptions = {
 
     styleNodes.forEach(({ id, content }) => {
       const scssName = id.substring(id.lastIndexOf('/') + 1, id.length);
-      const name = scssName.split('.')[0];
+      const [name] = scssName.split('.');
       fs.writeFileSync(`dist/css/${name}.css`, content);
     });
   },
@@ -32,7 +32,9 @@ const sassOptions = {
       grid: false
     })
   ])
-    .process(css)
+    .process(css, {
+      from: undefined
+    })
     .then((result) => result.css)
 };
 
@@ -75,7 +77,7 @@ const minifiedSassOptions = {
 
     styleNodes.forEach(({ id, content }) => {
       const scssName = id.substring(id.lastIndexOf('/') + 1, id.length);
-      const name = scssName.split('.')[0];
+      const [name] = scssName.split('.');
       fs.writeFileSync(`dist/css/${name}.min.css`, content);
     });
   },
@@ -85,7 +87,9 @@ const minifiedSassOptions = {
     }),
     cssnano()
   ])
-    .process(css)
+    .process(css, {
+      from: undefined
+    })
     .then((result) => result.css)
 };
 
```

**Comment by rwwagner90** [comment]
Thanks @peterblazejewicz. I made those changes. I had originally intended to come back through after this was merged and work on lint and warnings, but might as well do it now 😃

**Comment by rwwagner90** [comment]
@chuckcarpenter @TrevorBurnham I'm planning to merge this in today, if there are no objections. I want to get this first conversion in, so we can start to make progress testing smaller bits of the code in smaller PRs.

**Pull request merged**
